# Generated by Django 5.2.7 on 2025-10-19 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttackLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('raw_json', models.JSONField()),
                ('source_ip', models.CharField(blank=True, max_length=45, null=True)),
                ('raw_text', models.TextField(blank=True, null=True)),
                ('processed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ClassifiedAttack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mitre_id', models.CharField(blank=True, max_length=50, null=True)),
                ('attack_family', models.CharField(max_length=200)),
                ('confidence', models.FloatField(default=0.0)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='classification', to='hexaShiftApp.attacklog')),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('classified', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='hexaShiftApp.classifiedattack')),
            ],
        ),
    ]
